# Generated by Django 5.0.2 on 2024-02-22 08:48

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_alter_blogs_date_alter_blogs_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
