# Generated by Django 5.0.2 on 2024-02-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0003_alter_blogs_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
