# Generated by Django 5.0.2 on 2024-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0004_blogs_status_alter_blogs_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.TextField(max_length=3000),
        ),
    ]
