# Generated by Django 5.0.2 on 2024-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0005_alter_blogs_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='status',
        ),
    ]
