# Generated by Django 5.0.2 on 2024-02-23 07:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0006_remove_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
